#!/usr/bin/zsh

#sshpass -p "rob.log" scp motor-node.py rob@robotpi.local:/home/rob/RobotHttpNode/
#sshpass -p "rob.log" scp camera-node.py rob@robotpi.local:/home/rob/RobotHttpNode/


sshpass -p "rob.log" ssh rob@robotpi.local "rm -r /home/rob/Control.py/"
sshpass -p "rob.log" rsync -pr --exclude="__pycache__" Control.py/* rob@robotpi.local:/home/rob/Control.py/

